### ISSUE TITLE
Add Django 2.0 to the list

### ISSUE THREAD

**Issue by Eric-Arellano** [python3statement/python3statement.github.io#100]
As of December 2, the newest version of Django no longer supports Python 2. This is one of the largest Python libraries, so should be added to the list.

Do any moderators know the maintainers to Django?

https://docs.djangoproject.com/en/2.0/releases/2.0/

**Comment by mscuthbert** [comment]
See discussion in #21 and #23  -- we need a commitment also to stop supporting 2.7 in 2020 as well as a Py3 only release for the current wording of the statement.

(On Django 2.0 for a recent project -- so nice! :-)  )

**Comment by mscuthbert** [comment]
The project has, I think rightly, left "stop supporting" somewhat up to the discretion of the signatories.  For my project (music21), I'll certainly keep answering a question on the mailing list related to an older version using Py2 code, but I won't modify my code to make any Py2 issue easier.  When in 2020 to drop is also a tiny bit vague since while it looks like Jan 1, 2020 is going to be the EOL for Py2.7, that's still not set in stone.  So I don't think that when Django does decide to change "at least until April 2020" to "April 2020" I don't think anyone on this project will prevent them from signing.  But it does take an active signing statement on the part of a Django developer.

**Comment by Eric-Arellano** [comment]
Great. @mscuthbert do you or any of the other moderators perhaps know Django developers? I can look around for how to contact them, but imagine the request would come off better from someone they already know.

**Comment by mscuthbert** [comment]
Nope, and I don't know of anyone else here who has had success in getting these very busy people to sign on.  :-)  Might be better to get other non-scientific projects on the statement first?

**Comment by Eric-Arellano** [comment]
@Carreau it looked like you had reached out to a Django developer back in 2016 per #23? Now that they seem to have gotten more specific with their [timeline](https://www.djangoproject.com/download/#supported-versions), perhaps you could reach out to them again? cc @asmeurer 

@mscuthbert another good project would be getting Flask to make Python 3 the default in its [documentation](http://flask.pocoo.org/docs/0.12/python3/#python3-support), instead of having a special little section for how to support Py3..

**Comment by Carreau** [comment]
We reached out to them, see discussion in #95, and so far they are still "No". They don't see the benefit of adding their project here, or at least there is no consensus. We'd likely need an advocate to get preach and request the Django mailing list, but we should not insist too much, it is their choice.
