### ISSUE TITLE
Engage the discussion on broader channels?

### ISSUE THREAD

**Issue by fmaussion** [python3statement/python3statement.github.io#11]
I strongly support this initiative, thanks a lot!

I was wondering if you are willing to advertise this more, or if you'd rather wait for the text to be more mature? I came to this through the mpl-devel mailing list, but I think it's worth advertising the initiative on other channels as well: pydata, numpy, comp.lang.python, etc...

**Comment by Carreau** [comment]
Hi @fmaussion 

We are in stealth mode for now, we want to polish the site a bit before "going public", and get a few big project to sign up.

We've been contacting main developers of a few project privately, you've seen mpl, we are also reaching to SymPy that we know are pro Python 3, SciKit Bio, then we'll try to reach to other project. 
If you know of some that might be interested, then we can ask a broader community, more publicly. 

Imho, pydata and numpy channels will be one of the last bastion that will resist to the transition, 
I'll reach to some of their dev personally, when  that are literally seating 2 seats to my right.

One thing we don't want is have a language, or information that would : 
  1) frustrate Python 2 supporters
  2) Scare users

I'm also wondering if we should have a section of project/developer that do support what we are doing, but have no choice as they are under management pressure/have no choice.

And maybe a section for people/developper that support us, but have no project they maintain ? 

How does that sounds ?

**Comment by fmaussion** [comment]
Thanks @Carreau, I understand. I don't think there's much more you can do about the initiative but trying to convince some other (major) projects to jump in. Until now, Thomas' post on mpl-devel didn't raise any flame war...

I agree that when 5 or more of the major scientific python projects will be on the list, the initiative will have even more impact.

For what my opinion is worth (I am still fairly new to Python), I don't understand why it is such a big deal. You are not forbidding legacy python, you are just stopping to add new features to it, and for very good reasons. Like the gnome2 or windows XP supporters, it will still be possible for py2 supporters to enjoy the use of ipython and jupyter with py2 for the decades to come, but without the fancy new stuffs. Most people will cope with that, and it shouldn't be the problem of voluntary OSS developers to take care of that.

I don't think that I can do much but if I can do anything to help, let me know!

**Comment by Carreau** [comment]
> For what my opinion is worth (I am still fairly new to Python), I don't understand why it is such a big deal. You are not forbidding legacy python, you are just stopping to add new features to it, and for very good reasons. Like the gnome2 or windows XP supporters, it will still be possible for py2 supporters to enjoy the use of ipython and jupyter with py2 for the decades to come, but without the fancy new stuffs. Most people will cope with that, and it shouldn't be the problem of voluntary OSS developers to take care of that.

It's a complex problem, 

For the first things the Python packaging is much better nowdays that it was a few years ago, and there is still (I think) a strong fear that just `pip install --upgrade` will break all the things. 
This has been a huge pain at the beginning of Python3 where people would just upgrade their python and get a broken system. 

There is also the fact that it was much more painful to migrate to Python 3 a few years back, as `u''` prefix were not working, and many things that are now taking from granted (like six, python_modernize), were not available. So writing single source python, or even just moving to Python 3 was a really hard process. 

People are still under this impression.

You can add the fact that many people don't have the choice, their sysadmin have python 2.7 on all their centos 6 distribution, and thay don't even have the choice, or they literally have millions of line of code that would need to ported/validated. 

It is normals in these case to still want to get updates, bug fixes, new features, as otherwise you feel left behind. It's just difficulties realizing that you've already been kind of left behind by being on 2.7. 

It is also hard to accept that some of us, even if OSS developers, are (partly) paid to work on our projects, and hence think that we ought to support Python 2.7, it just difficult to realize that we also do have deadline and project to deliver. 

All these are things that are just hard to realize, and at some point you can understand and sympathize with people on Python 2. 

Already reaching here and asking what you can do is a huge step forward. We'll likely have concrete things to do  soon, we'll be happy to get your help !

**Comment by terryjreedy** [comment]
First, I want to thank the organizers of this project and website.  I see it as having three values.  First, supporting the core developers, who have gotten more flak than we should have.  Second, informing developers that is it alright to drop 2.x support; they are not the only ones.  Third, informing users about what is coming.

Is this still in stealth mode?  2.7 EOL is just 16 months away.  But I don't see listed, for instance, Django, which has already dropped 2.7 for its new feature branch, 2.x, and has scheduled end of life for its bugfix branch in for April, 2020.  https://code.djangoproject.com/

**Comment by Carreau** [comment]
> First, I want to thank the organizers of this project and website. I see it as having three values. First, supporting the core developers, who have gotten more flak than we should have.

Thanks, it is great to be of help, you are all doing awesome work on Core Python.

> Second, informing developers that is it alright to drop 2.x support; they are not the only ones. Third, informing users about what is coming.

One other key page is the practicality section http://python3statement.org/practicalities/ it tell library author how to prep their library so that Python 2 users still get the latest functioning version (`python_requires` metadata and other tips).

> Is this still in stealth mode? 

Hum, no we gave talks at [pybay](https://www.youtube.com/watch?v=3i6n1RwqQCo) and [pycon](https://www.youtube.com/watch?v=2DkfPzWWC2Q), but there is just so much we can do, and travelling to conference is not always possible. Anyone is welcome to reuse any material and present anywhere. 

> But I don't see listed, for instance, Django, which has already dropped 2.7 for its new feature branch

Django said no explicitly (#95 and #100), IIRC they don't see the benefit for them of being added there. One of the agreement is we wouldn't add a project without their consent.

We're still happy to get any exposure or help we can get (happy to give commit right), would love to get more support or exposure from core Python, but that often requires a champion to get even small things in (no criticism, just everyone busy)

**Comment by mscuthbert** [comment]
The statement is a commitment from developers to drop support for Python 2 by 2020; Django hasn't necessarily stated that they will no longer support their 1.X branch or release new versions of it later.

What could be done if the maintainers wanted to is to note somewhere, "Major projects that have not signed the statement but whose latest releases only support Python 3 include Django, ..., ..."  That would not imply a commitment to the statement or its principles, but show that there is a larger movement afoot beyond the names on the list.

(As a practicality, if someone discovered in 2021 that one of their old Py2 supporting versions had a bug that deleted people's hard drives on a new OS version, I don't think any contributor to the list would banish them if they rushed out a patch for that even though they've pledged not to support it)

**Comment by takluyver** [comment]
Yup, the main reason Django is not there is that they decided not to be.

At present, we haven't had many projects that are doing something similar but didn't want to sign the statement, so I wouldn't worry about noting them separately.

**Comment by Carreau** [comment]
Thanks, 

closing then. Feel free to tweet advertise and link to here, as well as not write Python 2 code.

Closing to clean up issue, but we can of course keep commenting.
