### ISSUE TITLE
the web by django ?

### ISSUE THREAD

**Issue by linpan** [python3statement/python3statement.github.io#196]

**Comment by takluyver** [comment]
Are you asking about adding Django to the statement? Last time we asked the maintainers, they declined to put Django's name on it (see #95). But that was a couple of years ago now; if someone wants to ask them again, they might have a different view now.

**Comment by hugovk** [comment]
https://www.djangoproject.com/download/ says:

> We recommend using the latest version of Python 3. The last version to support Python 2.7 is Django 1.11 LTS.

And Django 1.11 reaches end of extended support in April 2020:

![image](https://user-images.githubusercontent.com/1324225/55795541-bb162980-5ad0-11e9-894b-4f725d57460c.png)

**Comment by mscuthbert** [comment]
I suppose we could change the statement to include "Projects that have pledged to drop support for Python 2 or have already done so".  This would not include Django until whenever 1.11LTS actually gets the end of extended support (April 2020).  But for now, Django hasn't signed or shown an interest in signing and they wouldn't fit the second category ("signing by actions")

Again, to be clear, projects have only pledged to drop by end of 2020, not by Jan 1, since the exact Python 2.7 end date was established after this project launched.

**Comment by hugovk** [comment]
I don't think we should to change the statement, dozens have signed the current one and it'd take a long time to check if they agree to the new one.

And we wouldn't need to change it for Django to sign it, 1.11 LTS is EOL in April 2020, and in scope.

I think the end of 2020 is a good target for projects to aim for (and anyway, all but one on the timeline are dropping before the start of 2020).

**Comment by hugovk** [comment]
Please see PR https://github.com/python3statement/python3statement.github.io/pull/277.

**Comment by mscuthbert** [comment]
Django has not signed the statement, so unless we change the statement (as I proposed above), we can't add them to it.  This has come up several times and always been rejected.
