### ISSUE TITLE
Non-Scientific Python Projects?

### ISSUE THREAD

**Issue by mhils** [python3statement/python3statement.github.io#21]
Thanks for the great initiative. From what I understand the statement is currently worded very much towards the scientific Python stack. Are there any plans to extend the scope to Python libraries in general?

**Comment by Carreau** [comment]
Hi @mhils,  

> Thanks for the great initiative

Thanks for the kind words. 

> From what I understand the statement is currently worded very much towards the scientific Python stack [...]

Yes we worded the statement mostly toward Scientific Project as this is the crowd we know, and we were unsure how much adoption there would/can be outside of these circle, so we left it as is even if we had the discussion. We are of course welcoming anybody that would like to add their project here, and we can likely reword or have an addendum that explain that this is not limited to Scientific Python. 

If you have any idea on how to convey that meaning, they are welcome, and we would appreciate if you know of any project that would agree to sign the statement, or were you think we could at least engage the discussion. 

Thanks !

**Comment by mhils** [comment]
We would immediately sign this for @mitmproxy, but unless there's significant support from other non-scientific projects, it probably makes sense for you to keep the wording as strong as it is. "Major parts of the scientific stack" feel much stronger than "some subgroups within the Python ecosystem".

Maybe let's just leave this issue open for now and see if other non-scientific projects would be interested (cc @Lukasa, @kbandla)?

**Comment by Lukasa** [comment]
I'd certainly be open to this, with one caveat: PyPy is enormously important to me and my users, so my ability to honour this pledge would be in jeapordy if PyPy doesn't get the funding required to catch up to CPython. 

FWIW, I also think I'd have to say that requests/urllib3 are exempt because they are the foundation of pip, which sadly has to keep supporting older Pythons for security reasons.

**Comment by takluyver** [comment]
I'm torn. On the one hand, it was pointed out (#23) that Django is already planning a final Python 2 compatible release in a similar timeframe, so we could potentially get them on the list, which would be a big win.

On the other hand, I think the scientific Python community is in a relatively strong place to do this - text issues don't tend to trouble us as much, and the foundational packages like numpy gained Python 3 support quite early on, so there's been a while for more specific packages to adapt. PyPy is also not used much in this world, because we're already invested in other ways of speeding code up, and they don't tend to play well with PyPy.

We could leave the statement as is and add a couple of non-scientific projects (after all, part of the reason we like Python is the broad ecosystem - these worlds are not completely separate). Or maybe we should just go the whole hog and make it open to any projects - especially if we could get Django on board.

I do really hope PyPy gets the funding to catch up to a recent version of the language.

**Comment by Carreau** [comment]
My vote is to be in general open to non-scientific project to sign. I think we use enough non scientific based project in general. 

Pypy has this weird behavior where they are still trying to get compatibility with Python 3.3 then 3.4 instead of directly targeting the latest Python3.

**Comment by sigmavirus24** [comment]
> Pypy has this weird behavior where they are still trying to get compatibility with Python 3.3 then 3.4 instead of directly targeting the latest Python3.

So, I can sympathize because the "latest Python3" changes every 1.5 years and PyPy3 isn't really well funded at the moment. So as far as volunteer efforts go, it's easier to hit one fixed goal instead of trying to change the goal every 1.5 years. If compatibility with 3.3 means an easier transition for them to 3.4, then that's fine by me. I don't have the time to help but definitely wish I did.

I'll say for me that most of the projects I maintain (with some exceptions) will happily drop Python 2 support in 2020. (Flake8, mccabe, and many others) So if the scope moves more towards "all Python projects" I'd be happy to cosign this.

**Comment by takluyver** [comment]
Thanks @sigmavirus24 

Does anyone here know any of the Django developers and want to ask them if they're interested in signing the statement? If Django was willing to join, I think we'd probably drop the language that refers to scientific projects specifically.

**Comment by bdarnell** [comment]
(Coming here from a suggestion in tornadoweb/tornado#2219)

Tornado 6.0 will be dropping Python 2 support, so if you decide to expand this statement to projects that are only indirectly a part of the scientific stack, we'd be on board.

**Comment by Carreau** [comment]
I submitted #99 that pick a commit from #95 and widen the scope.
Let me know what you think (and happy holidays as well)

**Comment by Carreau** [comment]
#99 has been merged, the statement is now more general, we would happily get Tornado and Mitmproxy added.
