### ISSUE TITLE
A "Thank You" sign-off and archive?

### ISSUE THREAD

**Issue by mscuthbert** [python3statement/python3statement.github.io#292]
Now that it's 2024 and the Python 3 move has been a big success -- how about one last PR to give a closing update to the project -- what its aims were, how important the support of projects (both big and small) were to the adoption of Python 3-only work, and how projects are continuing to develop, move beyond old-version compatibility, and move Python-based projects into a more robust, faster running, and continually developing world, or something like that.  And then say that no more projects to be listed -- this is a historical archive etc.

Thoughts from other/original maintainers?  

Good work to everyone who first thought of this project and those who contributed along the way.  Congrats!

**Comment by asmeurer** [comment]
BTW I own the domain python3statment.org. It expires in November, but I don't have any issues keeping it around for historical purposes if people feel that's important.

**Comment by Carreau** [comment]
No objections from me, do you want to send a PR ?

**Comment by asmeurer** [comment]
That's a good idea. I am swapping things around now.

**Comment by asmeurer** [comment]
A little historical context, which could be useful for the sign off message, since many (most?) Python programmers today weren't around in the community ten years ago. In early 2016 when this site was created, the position of Python 3 in the ecosystem was still unclear. Some popular libraries still did not support it, and almost all still supported Python 2. The first version of Python 2 was released in 2008, and by 2016, the latest version was 3.5, a quite usable version (see https://www.python.org/doc/versions/). Guido had originally stated that Python 2.7 would stop being supported in 2015, but by 2014, this was extended to 2020, because the adoption by then was still quite low. (I'm sure someone could dig up some actual numbers here)

This indeed made many people quite nervous that Python 3 adoption might never happen. It's not even clear what this would have meant for the ecosystem if it had occurred. Would the CPython have been forced to continue Python 2 support forever, effectively splitting the language (similar to Perl and Raku)? Would the extra burden of maintenance have caused people to move to other languages, killing off the community? Would a major player fork Python 2 and split the community that way? There were also some people in the community who were loudly [outspoken against Python 3](https://lucumr.pocoo.org/2011/12/7/thoughts-on-python3/) (some with legitimate technical concerns, but the FUD was nonetheless very real). 

As a user and a maintainer, I saw the problem as this: most end-users were still using Python 2. It was the "default" for most installation methods, and even if they wanted to use Python 3, the lack of support by some libraries meant they would still need to consider Python 2 support. OTOH, libraries were hesitant to support Python 3. This is because at the time, supporting Python 3 meant supporting two versions at once. This became easier as the general consensus moved from doing this with 2to3 to using tools like six, as well as some features in newer Python 3 versions that made compatibility easier (like `u`-prefixed strings), but the friction was still there. I often heard maintainers express the opinion that supporting Python 3 was a waste of effort and maintenance burden given that there were almost no users. 

This "chicken" situation became especially concerning to me. It was clear to me that library maintainers needed to move first, not users, because users are effectively forced to use whatever their libraries support. But library maintainers were also playing chicken with each other, especially against core libraries that are dependencies of many things in the stack (e.g. numpy). 

This is why I [tweeted](https://twitter.com/asmeurer/status/712304912428875776) that libraries should sign a statement stating that the will drop Python 2 support by 2020. (I'm still unclear if my tweet was the direct inspiration for @Carreau to create this site or if he had the idea independently). My idea is that this would create a Nash Equilibrium that would remove the "I'll wait to see what everyone else is doing first" feeling from the ecosystem. I also wrote a [blog post](https://www.asmeurer.com/blog/posts/moving-away-from-python-2/) about my thoughts, which was at the top of Hacker News and garnered [a lot of controversy](https://news.ycombinator.com/item?id=11738470). Those HN comments will give you a good idea of what the general feeling on Python 3 was like back then.

Remarkably, the idea actually worked and as more people signed on to the statement, it generated momentum. I don't know how much it actually mattered in the end, but I think it did at least help to convince some projects that dropping Python 2 support was "OK" since "everyone else is doing it too".

Also, I don't want to claim any credit here. My main contribution (aside from the idea) was buying a domain so that the site looked more legitimate. The actual work on the site was done by @Carreau and @takluyver.

**Comment by asmeurer** [comment]
By the way, I suck at configuring DNS. I've tried to set python3statement.org to 301 redirect to python3statement.github.io, but I think I've only managed to break it.

**Comment by asmeurer** [comment]
@Carreau @takluyver if either of you know how to work namecheap and fix this you're both managers on the domain https://ap.www.namecheap.com/domains/domaincontrolpanel/python3statement.org/advancedns

**Comment by takluyver** [comment]
It looks like the redirect works from plain HTTP http://python3statement.org , but not on HTTPS. And I guess the browser either prefers HTTPS or remembers that it has previously seen the site on HTTPS, so it won't readily use plain HTTP.

It looks like this is [a known limitation](https://www.reddit.com/r/NameCheap/comments/motl8n/redirecting_from_https_does_not_work/) of Namecheap's built in redirects.

There's a site domain-forward.com which [offers to solve this](https://domain-forward.com/2023/07/14/namecheap-domain-redirect-everything-you-should-know/). It appears to be free up to 200k requests per month; I guess python3statement isn't getting huge amounts of traffic any more. I guess that's easier than setting up a server with SSL somewhere just to serve redirects?

**Comment by Carreau** [comment]
I guess we can do a non-dns redirect, and inject a tiny bit of JS ?

**Comment by asmeurer** [comment]
Wow, thanks for the info Thomas. I set it up on domain-forward and it seems to work now.

**Comment by takluyver** [comment]
Nice one, thanks Aaron! The redirect works for me.

**Comment by Carreau** [comment]
I've sent PRs to a couple of place to update URLs, 

I know of at least xarray and imageio that reference the 
```
xarray/doc/whats-new.rst
4561:  - `Python 3 Statement <http://www.python3statement.org/>`__

imageio/docs/user_guide/drop27.rst
16:.. _python3-statement: http://www.python3statement.org/
```

(also the www. redirect might be incorrect as it raise an invalid certificate)

**Comment by mscuthbert** [comment]
> BTW I own the domain python3statment.org. It expires in November, but I don't have any issues keeping it around for historical purposes if people feel that's important. 

If you'd be willing to renew for one more year my sense is that this would be enough time for the SEOs to point everything to the new redirect. November may be enough time but in my experience less than six months can be dicey for that. Glad to cover the cost if it's a financial burden. (Seeing others on this site--it was only about 6-8 then--gave me the courage to move music21 to Py3 only, a move I've never regretted as I regained my joy of developing in Python when I did so; I was happy to sign and wear the pledge boldly!) 

Whatever text is decided on (I've loved hearing the stories of how this came to be, stories I never knew until now) let's also put it in the README. Hosting of the website may disappear somewhere in the deep future but a git clone will survive an order of magnitude longer. 

I was trained as a 14th c music scholar for my PhD and I know and depend on the foresight of people 700 years ago who wrote down things that others didn't think would be worth preserving. When the history of computation 1950-2050 is written somewhere in the distant future I think Python will be part of that history and I think this project will be a contributor to that story. I saw how Perl 5 vs 6 killed off a thriving and active community and that could have happened again if it weren't for the boldness of some devs and their willingness to saw "we have your back" to those who followed.

**Comment by takluyver** [comment]
In a similar vein to Aaron's 'playing chicken' metaphor, I definitely remember talking about a herd of wildebeest preparing to cross a crocodile-infested river - one setting out by itself (i.e. one project dropping support for Python 2) is going to have a bad time, but there's safety in numbers when the whole lot charge across at once. Rather melodramatic, I guess, but that was how I envisaged the statement. :laughing:

**Comment by takluyver** [comment]
#293 is my attempt at adding this - do have a look.

**Comment by Carreau** [comment]
We also did a bunch of work upstream for pip and warehouse to support `python_requires` :-) But yes, I think as a big project it was scary, but I think all the work that was done to both lay the technical work and the appease fear of users stuck on python2, the transition was much smoother than expected.

**Comment by asmeurer** [comment]
www redirect should be fixed.

**Comment by asmeurer** [comment]
OK, I went ahead and renewed the domain for 1 year. After that I will let it expire.

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
OK, the 'history' section is up, and I've also updated the readme. Thanks @mscuthbert for the suggestion!
