### ISSUE TITLE
Numpy timeline proposal

### ISSUE THREAD

**Issue by fmaussion** [python3statement/python3statement.github.io#89]
Just in case you missed it, and for documentation purposes:

https://mail.python.org/pipermail/numpy-discussion/2017-November/077341.html

**Comment by takluyver** [comment]
Thanks for letting us know - I don't follow numpy development.

On 7 Nov 2017 9:19 a.m., "Fabien Maussion" <notifications@github.com> wrote:

Just in case you missed it, and for documentation purposes:

https://mail.python.org/pipermail/numpy-discussion/2017-November/077341.html

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/python3statement/python3statement.github.io/issues/89>,
or mute the thread
